version: '3.9'

services:
  jacem-chaieb-me:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=3000
    command: [ 'yarn', 'dev' ]
    volumes:
      - ./:/home/node/app
      - node_modules:/home/node/app/node_modules
    ports:
      - 24678-24679:24678-24679 # Vite HMR ports
    labels:
      # Traefik
      traefik.enable: true
      traefik.http.services.jacem-chaieb-me.loadbalancer.server.port: 3000
      # HTTP
      traefik.http.routers.jacem-chaieb-me.entryPoints: web
      traefik.http.routers.jacem-chaieb-me.rule: Host(`jacem.dev.localhost`)
      traefik.http.routers.jacem-chaieb-me.service: jacem-chaieb-me
      traefik.http.routers.jacem-chaieb-me.middlewares: redirect-to-https
      # HTTPS
      traefik.http.routers.jacem-chaieb-me-ssl.tls: true
      traefik.http.routers.jacem-chaieb-me-ssl.entryPoints: websecure
      traefik.http.routers.jacem-chaieb-me-ssl.rule: Host(`jacem.dev.localhost`)
      traefik.http.routers.jacem-chaieb-me-ssl.service: jacem-chaieb-me
    networks:
      traefik-network:

volumes:
  node_modules:

networks:
  traefik-network:
    external: true
    name: traefik-network
