name: Deploy to a temporary url

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '**docker**'
      - '.github/**'
      - '.gitignore'
      - '.vscode/**'
      - 'README.md'
      - 'justfile'
      - 'compose.yaml'

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' && github.event.pull_request.head.repo.full_name == github.repository }}
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: 20
      - run: yarn install
      - run: yarn generate
      - uses: FirebaseExtended/action-hosting-deploy@0cbcac4740c2bfb00d632f0b863b57713124eb5a #v0.9.0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JACEM_CHAIEB }}
          projectId: jacem-chaieb
